### ISSUE TITLE
plothist and boost_histogram incompatibility

### ISSUE THREAD

**Issue by masterfelu** [cyrraz/plothist#173]
When I try to run this code, I get a `ValueError: The bins of the histograms must be equal.`

```
import matplotlib.pyplot as plt
import boost_histogram as bh
from plothist import (
    make_hist,
    plot_comparison,
)

nbins=10
gen_hist = make_hist(range=(-1,1),bins=nbins)
uni_hist = bh.Histogram(bh.axis.Regular(nbins, -1, 1))
    
_,ax=plt.subplots()
plot_comparison(gen_hist, uni_hist, ax=ax, comparison="ratio")
```

plothist version is 1.2.5, boost-histogram version is 1.4.0

**Comment by 0ctagon** [comment]
Hi @masterfelu, thank you for asking this question.
If you print the axis of both histograms, you can indeed see that they are not the same:
```
print(gen_hist.axes[0])
> Regular(10, -1, 1, underflow=False, overflow=False)
print(uni_hist.axes[0])
> Regular(10, -1, 1)
```
You can also print the histograms in the terminal to see that the first and last bins have underflow and overflow. By default in plothist, we set both to False (see [here](https://plothist.readthedocs.io/en/latest/documentation/documentation.html#plothist.histogramming.create_axis)) to have the same behavior as matplotlib.

To fix the `ValueError` you get, you just have to do:
```
uni_hist = bh.Histogram(bh.axis.Regular(nbins, -1, 1, overflow=False, underflow=False))
```
