### ISSUE TITLE
Use Python libraries over `wget` to download files

### ISSUE THREAD

**Issue by matthewfeickert** [cyrraz/plothist#175]
In 

https://github.com/cyrraz/plothist/blob/06b24cdbf4676efe914ec514be720635e942a2eb/src/plothist/scripts/install_latin_modern_fonts.py#L24-L26

and 

https://github.com/cyrraz/plothist/blob/06b24cdbf4676efe914ec514be720635e942a2eb/src/plothist/scripts/make_examples.py#L121-L128

`wget` is called as a subprocess to download files. Instead of requiring an outside utility, it would be nicer to use a Python standard library like `urllib` or an external library like `requests`. While `wget` is abundantly used, it is preferable to have all dependencies clearly specified at install time such that installing in a Linux container environment isn't a suprise or trial-and-error situation.

**Comment by matthewfeickert** [comment]
Same goes for `unzip`

https://github.com/cyrraz/plothist/blob/06b24cdbf4676efe914ec514be720635e942a2eb/src/plothist/scripts/install_latin_modern_fonts.py#L170-L180

**Comment by 0ctagon** [comment]
We got the recommendation to put the fonts (along with our fake dataset) in a separate package as mplhep does with mplhep-data. For now, I replaced wget and unzip with the python version in https://github.com/cyrraz/plothist/pull/176.

**Comment by cyrraz** [comment]
Thank you. The fix is merged and a new patch release (1.2.6) was published on PyPI.
